### ISSUE TITLE
[BUG] Auto Waypoints stopped working in 1.17.9 Stable

### ISSUE THREAD

**Issue by deafro5** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.CampaignCartographer#32]
**Describe the Bug:**
When touching  items (surface deposits, berry bushes, traders) the game no longer adds automatic waypoints. Friends have tried to install mod new, but same issues happen. Manual Waypoint system and Settings menu still seem to work.

**To Reproduce:**
Steps to reproduce the behaviour:
Start or join a game.
Make sure automatic waypoints are enabled in the .wpauto dialogue
Do something that would create a waypoint

**Expected Behaviour:**
A waypoint is created

**Additional Context**
Was working in 1.17.8, no longer working in 1.17.9

**Comment by ApacheTech** [comment]
From what I've been able to test, the auto-waypoints still work. I did see that Berry Bushes seem to register interactions only when ripe now.

You can get strange issues if the server and client have different versions of the mod installed. If you're playing on an SMP, that may be the issue. Find out which version the server is running, and the clients will need the same.

Unfortunately, because of limitations with the way the game handles mods, it not currently possible to update mods like this one, automatically, on the client. The mod will not be downloaded with the rest of the "per-server" mods.

That would be my first point of call; check the versions. If all the versions are good, then please check the log files of any client that can't use AutoWaypoints. If an error has occurred, I'd expect an entry to say something like "Entry point not found", or "Error when starting ModSystem, AutoWaypoints". Something like that. It would be a Harmony patching error saying it couldn't find a method, or that it couldn't apply the patch.

Post back here with anything you find. You can upload the whole log files, if you like. `client-main.txt`. and `client-debug.txt`.

**Comment by deafro5** [comment]
Hi Apache, SW Engineer here myself. It seemed to work again a few days later. I had time to "reload mods" via the mod menu. but not sure what difference that would have made. I've seen this has happened in the past, I'm curious if it happens because of some weird issues when the new main patch is installed via the installer. I'll keep an eye out in the future.

Just for informational, It wasn't a Server/Client. It was Single Player, opened up to the internet to play with friends. But it seemed to not work initially in single player, and other friends who were playing with had the same issue.

**Comment by ApacheTech** [comment]
It's one reason I try to remove old versions from ModDB as soon as possible after a new release. There's no real support for hybrid mods at the moment. I'm hoping that will change.

Keep an eye out for any exceptions in the logs, and if you post any stack traces you find, that would be really useful. Nothing has changed, within the codebase, that should break anything in the mod. Although, I'll be bringing out a parity update soon, that will fix some bugs within my MDK.

**Comment by FreeMoonshadow** [comment]
I have the same issue, auto way points seems to just stop working and on another occasion restarts  - sadly I haven't noticed any pattern. Hypi had this issue when playing on the Rusty Gear servers on occasion as well. I tried reload mods and that didn't work - i'll try and play around with it a bit

**Comment by ApacheTech** [comment]
> I have the same issue, auto way points seems to just stop working and on another occasion restarts - sadly I haven't noticed any pattern. Hypi had this issue when playing on the Rusty Gear servers on occasion as well. I tried reload mods and that didn't work - i'll try and play around with it a bit

Have you had any luck in tracking down a reproducible pattern for this bug?
